# Generated by Django 3.0.3 on 2020-03-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20200303_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='diary.StatusEntry'),
        ),
    ]
