# Generated by Django 3.0.3 on 2020-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20200304_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusentry',
            name='ignored_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
